site_name: Learn OpenStack
site_url: https://www.patashale.in/learn-openstack/
site_author: Patashale™
site_description: Learn everything about OpenStack here at Patashale™.
repo_url: https://github.com/patashale/learn-openstack
repo_name: patashale/learn-openstack
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.footer

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/patashale
      name: Patashale™ on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/patashale
      name: Patashale™ on GitHub
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@patashale
      name: Patashale™ on Mastodon
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@patashale
      name: Patashale™ on YouTube
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@learn-openstack
      name: Learn OpenStack on YouTube

nav:
  - Home: index.md


copyright: Copyright &copy; 2023 Patashale™
